### PR TITLE
Branching Not Forking

### PR DESCRIPTION
**Pull request by scharfek**
Looks like I created a copy and forked this repo.  Adding mine back into the jt-courses.

### CODE REVIEW

**Comment by JoshuaToenyes** [comment]
😂  1 and 3 sound terrible! I'm going to say 2 is the lie.

**Review by pcook21 — COMMENTED** [review]
#2 is the lie

**Comment by ruggedstickman** [comment]
marathon, you're too skinny to run a marathon

**Comment by Steingraber** [comment]
Number 1 is a lie.

**Pull request merged**
