### PR TITLE
Add truths and one lie for Joshua Toenyes.

### PR DESCRIPTION
**Pull request by JoshuaToenyes**

### CODE REVIEW

**Comment by kdp0123** [comment]
I think skydiving is a lie.  Am I doing this right?

**Comment by JoshuaToenyes** [comment]
@kdp0123 You are "doing it" correctly! But I'm not going to tell you if you're correct on your guess yet :)

**Review by Rubi-M — COMMENTED** [review]
I would have to say you circumnavigating the globe sounds kind of suspicious so I'll go with that being the lie...unless of course you meant a miniature version of it...

**Comment by JoshuaToenyes** [comment]
> I would have to say you circumnavigating the globe sounds kind of suspicious so I'll go with that being the lie...unless of course you meant a miniature version of it...

@Rubi-M Vote recorded! I definitely did not mean a miniature version :)

**Comment by wardelltiffany** [comment]
My guess is that "circumnavigated the globe" is the lie.

**Comment by Christopherzero** [comment]
I also think skiing is the lie.

**Comment by JoshuaToenyes** [comment]
I think it's hilarious that no one has a problem believing the refrigerator 😂

**Comment by mckennaheasley** [comment]
I think number two is the lie. Something like you have been skydiving but you hated it.... Number 3 is definitely true.

**Comment by Steingraber** [comment]
I think that you loving skydiving is a lie.

**Review by pcook21 — COMMENTED** [review]
I think your love of skydiving is the lie

**Comment by ruggedstickman** [comment]
fridge, you hate the olympics

**Pull request merged**
