### PR TITLE
Two truths and one lie homework RubiM

### PR DESCRIPTION
**Pull request by Rubi-M**

### CODE REVIEW

**Comment by Christopherzero** [comment]
i think being stung by a bee or wasp is the lie.

**Comment by JoshuaToenyes** [comment]
@Rubi-M you made another commit and deleted your file! Did you mean to do that?

**Comment by mckennaheasley** [comment]
I think the lie is the Canada one- that you have been.

**Comment by kdp0123** [comment]
I think the lie is that you have lived in 4 different states.

**Comment by Steingraber** [comment]
I think the lie is never having been to Canada.

**Review by pcook21 — COMMENTED** [review]
You've been to Canada and are just embarrassed to own it. Totally understandable. 
#1 is the lie

**Comment by ruggedstickman** [comment]
bee

**Pull request merged**
